"""Adding ip and terminal columns to countries table

Revision ID: 2265616535c3
Revises: 2cd98dfe9972
Create Date: 2025-08-24 05:07:11.169525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2265616535c3'
down_revision: Union[str, None] = '2cd98dfe9972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('ip', sa.String(length=20), nullable=True))
    op.add_column('countries', sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'terminal')
    op.drop_column('countries', 'ip')
    # ### end Alembic commands ###
