"""Adding ip and terminal columns to social_media table

Revision ID: 2cd98dfe9972
Revises: e48e4afa85c7
Create Date: 2025-08-24 04:59:06.098846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cd98dfe9972'
down_revision: Union[str, None] = 'e48e4afa85c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_media', sa.Column('ip', sa.String(length=20), nullable=True))
    op.add_column('social_media', sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_media', 'terminal')
    op.drop_column('social_media', 'ip')
    # ### end Alembic commands ###
