"""ArtowrkSchedule Table

Revision ID: 8845db1ec03a
Revises: 11d010440488
Create Date: 2025-08-24 20:05:41.738651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8845db1ec03a'
down_revision: Union[str, None] = '11d010440488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishing', sa.Column('type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishing', 'type')
    # ### end Alembic commands ###
