"""Correcting Tables´ attributes

Revision ID: b077202993be
Revises: c264b40aec25
Create Date: 2025-08-24 20:24:18.765725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b077202993be'
down_revision: Union[str, None] = 'c264b40aec25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishing', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('publishing', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('publishing', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('publishing', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishing', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('publishing', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('publishing', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('publishing', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###
