"""Correcting Tables´ attributes

Revision ID: c264b40aec25
Revises: f08c13199de9
Create Date: 2025-08-24 20:18:43.300748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c264b40aec25'
down_revision: Union[str, None] = 'f08c13199de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artwork_categories', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_categories', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artwork_categories', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artwork_categories', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artwork_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artwork_image', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_image', 'filename',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artwork_image', 'image_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artwork_image', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artwork_image', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artwork_image', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artwork_image', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artwork_owner', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_owner', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_owner', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artwork_owner', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artwork_owner', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artwork_owner', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artwork_schedule', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_schedule', 'publishing_id_target',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_schedule', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artwork_schedule', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artwork_schedule', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artwork_schedule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artwork_softwares', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_softwares', 'software_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_softwares', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artwork_softwares', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artwork_softwares', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artwork_softwares', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artwork_thumbnail', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_thumbnail', 'filename',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artwork_thumbnail', 'thumbnail_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artwork_thumbnail', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artwork_thumbnail', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artwork_thumbnail', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artwork_thumbnail', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artwork_topics', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_topics', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_topics', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artwork_topics', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artwork_topics', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artwork_topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artwork_video', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artwork_video', 'filename',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artwork_video', 'video_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artwork_video', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artwork_video', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artwork_video', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artwork_video', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artworks', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('artworks', 'mature_content',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('artworks', 'publishing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artworks', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('artworks', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('artworks', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('artworks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('categories', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('categories', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('categories', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('countries', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('countries', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('countries', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('countries', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('countries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('social_media', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('social_media', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('social_media', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('social_media', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('social_media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('softwares', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('softwares', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('softwares', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('softwares', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('softwares', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('topics', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('topics', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('topics', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('topics', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_categories', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('user_categories', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_categories', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_social_network', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_social_network', 'social_media_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_social_network', 'link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_social_network', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('user_social_network', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_social_network', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_social_network', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_softwares', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_softwares', 'software_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_softwares', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('user_softwares', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_softwares', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_softwares', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_topics', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_topics', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_topics', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('user_topics', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_topics', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('user_topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_topics', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_topics', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_topics', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('user_topics', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_topics', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_softwares', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_softwares', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_softwares', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_softwares', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('user_softwares', 'software_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_softwares', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_social_network', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_social_network', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_social_network', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_social_network', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('user_social_network', 'link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_social_network', 'social_media_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_social_network', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_categories', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('user_categories', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user_categories', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('user_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('topics', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('topics', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('topics', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('topics', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('softwares', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('softwares', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('softwares', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('softwares', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('softwares', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('social_media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('social_media', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('social_media', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('social_media', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('social_media', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('countries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('countries', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('countries', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('countries', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('countries', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('categories', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('categories', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('categories', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artworks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artworks', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artworks', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artworks', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artworks', 'publishing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artworks', 'mature_content',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('artworks', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artwork_video', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artwork_video', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artwork_video', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artwork_video', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artwork_video', 'video_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artwork_video', 'filename',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artwork_video', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artwork_topics', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artwork_topics', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artwork_topics', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artwork_topics', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_topics', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_thumbnail', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artwork_thumbnail', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artwork_thumbnail', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artwork_thumbnail', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artwork_thumbnail', 'thumbnail_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artwork_thumbnail', 'filename',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artwork_thumbnail', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_softwares', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artwork_softwares', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artwork_softwares', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artwork_softwares', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artwork_softwares', 'software_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_softwares', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_schedule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artwork_schedule', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artwork_schedule', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artwork_schedule', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artwork_schedule', 'publishing_id_target',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_schedule', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_owner', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artwork_owner', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artwork_owner', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artwork_owner', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artwork_owner', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_owner', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_image', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artwork_image', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artwork_image', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artwork_image', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artwork_image', 'image_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artwork_image', 'filename',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('artwork_image', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('artwork_categories', 'terminal',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('artwork_categories', 'ip',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('artwork_categories', 'status',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('artwork_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artwork_categories', 'artwork_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
