"""Adding image column to softwares table

Revision ID: e48e4afa85c7
Revises: e68454f87338
Create Date: 2025-08-24 04:56:04.476842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48e4afa85c7'
down_revision: Union[str, None] = 'e68454f87338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('softwares', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('softwares', 'image')
    # ### end Alembic commands ###
