"""Initial Migration

Revision ID: e68454f87338
Revises: 
Create Date: 2025-08-24 04:46:03.420794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e68454f87338'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_index(op.f('ix_countries_country_id'), 'countries', ['country_id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('publishing',
    sa.Column('publishing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('publishing_id')
    )
    op.create_index(op.f('ix_publishing_name'), 'publishing', ['name'], unique=True)
    op.create_index(op.f('ix_publishing_publishing_id'), 'publishing', ['publishing_id'], unique=False)
    op.create_table('social_media',
    sa.Column('social_media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('social_media_id')
    )
    op.create_index(op.f('ix_social_media_name'), 'social_media', ['name'], unique=True)
    op.create_index(op.f('ix_social_media_social_media_id'), 'social_media', ['social_media_id'], unique=False)
    op.create_table('softwares',
    sa.Column('software_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('software_id')
    )
    op.create_index(op.f('ix_softwares_name'), 'softwares', ['name'], unique=True)
    op.create_index(op.f('ix_softwares_software_id'), 'softwares', ['software_id'], unique=False)
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_index(op.f('ix_topics_topic_id'), 'topics', ['topic_id'], unique=False)
    op.create_table('artworks',
    sa.Column('artwork_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('mature_content', sa.Boolean(), nullable=True),
    sa.Column('publishing_id', sa.Integer(), nullable=True),
    sa.Column('has_images', sa.Boolean(), nullable=True),
    sa.Column('has_videos', sa.Boolean(), nullable=True),
    sa.Column('has_3d_file', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publishing_id'], ['publishing.publishing_id'], ),
    sa.PrimaryKeyConstraint('artwork_id')
    )
    op.create_index(op.f('ix_artworks_artwork_id'), 'artworks', ['artwork_id'], unique=False)
    op.create_index(op.f('ix_artworks_title'), 'artworks', ['title'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('professional_headline', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('artwork_categories',
    sa.Column('artwork_category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('artwork_category_id')
    )
    op.create_index(op.f('ix_artwork_categories_artwork_category_id'), 'artwork_categories', ['artwork_category_id'], unique=False)
    op.create_table('artwork_image',
    sa.Column('artwork_image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('image_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.PrimaryKeyConstraint('artwork_image_id')
    )
    op.create_index(op.f('ix_artwork_image_artwork_image_id'), 'artwork_image', ['artwork_image_id'], unique=False)
    op.create_table('artwork_owner',
    sa.Column('artwork_owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('artwork_owner_id')
    )
    op.create_index(op.f('ix_artwork_owner_artwork_owner_id'), 'artwork_owner', ['artwork_owner_id'], unique=False)
    op.create_table('artwork_softwares',
    sa.Column('artwork_software_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['softwares.software_id'], ),
    sa.PrimaryKeyConstraint('artwork_software_id')
    )
    op.create_index(op.f('ix_artwork_softwares_artwork_software_id'), 'artwork_softwares', ['artwork_software_id'], unique=False)
    op.create_table('artwork_thumbnail',
    sa.Column('artwork_thumbnail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.PrimaryKeyConstraint('artwork_thumbnail_id')
    )
    op.create_index(op.f('ix_artwork_thumbnail_artwork_thumbnail_id'), 'artwork_thumbnail', ['artwork_thumbnail_id'], unique=False)
    op.create_table('artwork_topics',
    sa.Column('artwork_topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('artwork_topic_id')
    )
    op.create_index(op.f('ix_artwork_topics_artwork_topic_id'), 'artwork_topics', ['artwork_topic_id'], unique=False)
    op.create_table('artwork_video',
    sa.Column('artwork_video_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('video_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.PrimaryKeyConstraint('artwork_video_id')
    )
    op.create_index(op.f('ix_artwork_video_artwork_video_id'), 'artwork_video', ['artwork_video_id'], unique=False)
    op.create_table('user_categories',
    sa.Column('user_category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_category_id')
    )
    op.create_index(op.f('ix_user_categories_user_category_id'), 'user_categories', ['user_category_id'], unique=False)
    op.create_table('user_social_network',
    sa.Column('user_social_network_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('social_media_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_media_id'], ['social_media.social_media_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_social_network_id')
    )
    op.create_index(op.f('ix_user_social_network_user_social_network_id'), 'user_social_network', ['user_social_network_id'], unique=False)
    op.create_table('user_softwares',
    sa.Column('user_software_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['softwares.software_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_software_id')
    )
    op.create_index(op.f('ix_user_softwares_user_software_id'), 'user_softwares', ['user_software_id'], unique=False)
    op.create_table('user_topics',
    sa.Column('user_topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_topic_id')
    )
    op.create_index(op.f('ix_user_topics_user_topic_id'), 'user_topics', ['user_topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_topics_user_topic_id'), table_name='user_topics')
    op.drop_table('user_topics')
    op.drop_index(op.f('ix_user_softwares_user_software_id'), table_name='user_softwares')
    op.drop_table('user_softwares')
    op.drop_index(op.f('ix_user_social_network_user_social_network_id'), table_name='user_social_network')
    op.drop_table('user_social_network')
    op.drop_index(op.f('ix_user_categories_user_category_id'), table_name='user_categories')
    op.drop_table('user_categories')
    op.drop_index(op.f('ix_artwork_video_artwork_video_id'), table_name='artwork_video')
    op.drop_table('artwork_video')
    op.drop_index(op.f('ix_artwork_topics_artwork_topic_id'), table_name='artwork_topics')
    op.drop_table('artwork_topics')
    op.drop_index(op.f('ix_artwork_thumbnail_artwork_thumbnail_id'), table_name='artwork_thumbnail')
    op.drop_table('artwork_thumbnail')
    op.drop_index(op.f('ix_artwork_softwares_artwork_software_id'), table_name='artwork_softwares')
    op.drop_table('artwork_softwares')
    op.drop_index(op.f('ix_artwork_owner_artwork_owner_id'), table_name='artwork_owner')
    op.drop_table('artwork_owner')
    op.drop_index(op.f('ix_artwork_image_artwork_image_id'), table_name='artwork_image')
    op.drop_table('artwork_image')
    op.drop_index(op.f('ix_artwork_categories_artwork_category_id'), table_name='artwork_categories')
    op.drop_table('artwork_categories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_artworks_title'), table_name='artworks')
    op.drop_index(op.f('ix_artworks_artwork_id'), table_name='artworks')
    op.drop_table('artworks')
    op.drop_index(op.f('ix_topics_topic_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_softwares_software_id'), table_name='softwares')
    op.drop_index(op.f('ix_softwares_name'), table_name='softwares')
    op.drop_table('softwares')
    op.drop_index(op.f('ix_social_media_social_media_id'), table_name='social_media')
    op.drop_index(op.f('ix_social_media_name'), table_name='social_media')
    op.drop_table('social_media')
    op.drop_index(op.f('ix_publishing_publishing_id'), table_name='publishing')
    op.drop_index(op.f('ix_publishing_name'), table_name='publishing')
    op.drop_table('publishing')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_country_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
