"""ArtowrkSchedule Table

Revision ID: f08c13199de9
Revises: 8845db1ec03a
Create Date: 2025-08-24 20:07:33.473841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f08c13199de9'
down_revision: Union[str, None] = '8845db1ec03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork_schedule',
    sa.Column('artwork_schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('publishing_id_target', sa.Integer(), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('schedule_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('terminal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.artwork_id'], ),
    sa.ForeignKeyConstraint(['publishing_id_target'], ['publishing.publishing_id'], ),
    sa.PrimaryKeyConstraint('artwork_schedule_id')
    )
    op.create_index(op.f('ix_artwork_schedule_artwork_schedule_id'), 'artwork_schedule', ['artwork_schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artwork_schedule_artwork_schedule_id'), table_name='artwork_schedule')
    op.drop_table('artwork_schedule')
    # ### end Alembic commands ###
